INSERT INTO tools_type (name) VALUES
('Aceite'), ('Señal'), ('Bomba'), ('Poción'), ('Elemento'), ('Desconocido');

INSERT INTO categories (name) VALUES
('Bestia'), ('Maldito'), ('Dracónido'),
('Constructo'), ('Híbrido'), ('Insectoide'),
('Necrófago'), ('Ogroide'), ('Relicto'),
('Espectro'), ('Vampiro');

INSERT INTO tools (name, id_type) VALUES
('Aard', 2),
('Aceite para bestias', 1),
('Aceite para constructos', 1),
('Aceite para dracónidos', 1),
('Aceite para espectros', 1),
('Aceite para híbridos', 1),
('Aceite para insectoides', 1),
('Aceite para malditos', 1),
('Aceite para vampiros', 1),
('Aceite para ogroides', 1),
('Aceite para relictos', 1),
('Aceite para vampiros', 1),
('Axia', 2),
('Bejín del demonio', 3),
('Bomba de dimerita', 3),
('Colmena', 3),
('Desconocido', 6),
('Estrella danzante', 3),
('Igni', 2),
('Miel blanca', 4),
('Oropéndola', 4),
('Polvo lunar', 3),
('Quen', 2),
('Sangre negra', 4),
('Simún', 3),
('Ventisca', 4),
('Viento del norte', 4),
('Yrden', 2);

INSERT INTO locations (name) VALUES
('Al sur de Novigrado'),
('Al sur de Valdetilo'),
('Bosque a las afueras de Oxenfurt'),
('Bosques'),
('Boxholm'),
('Campo del torneo'),
('Campos al sur de los Confines Lejanos'),
('Campos de batalla'),
('Castillo de Monte Grulla'),
('Castillos'),
('Cerca de cadáveres'),
('Cerca de Fyresdal'),
('Cerca de la aldea de Larvik en Hindarsfjall'),
('Ciudades'),
('Cloacas de Oxenfurt'),
('Cuerpos de agua'),
('Cueva cerca de Blandare'),
('Cueva cerca de Percha del Cuervo'),
('Cueva debajo del puerto de Kaer Trolde'),
('Cueva en Velen'),
('Cuevas'),
('Desconocida'),
('Desconocido'),
('Faro de Eldberg'),
('Fayrlund'),
('Hacienda von Everec'),
('Huerto Blanco'),
('Isla de las Brumas'),
('Isla del Palangre'),
('Junto a la cacería salvaje'),
('Kaer Morhen'),
('Montañas del Dragón'),
('Mundo de Gaunter'),
('Novigrado'),
('Orfanato La Compasión'),
('Orillas'),
('Oxenfurt'),
('País de las Mil Fábulas'),
('Percha del Cuervo'),
('Poblados'),
('Redania'),
('Residencia Moldavie'),
('Ruinas abandonadas'),
('Ruinas élficas'),
('Ruinas mágicas'),
('Skellige'),
('Spikeroog'),
('Toussaint'),
('Valdetilo'),
('Valle de Kaer Morhen'),
('Velen'),
('Zonas montañosas');