INSERT INTO loots (name) VALUES
('Addan Deith'),
('Ami'),
('Armadura de Zireael'),
('Azufre'),
('Cabello de aparición nocturna'),
('Cabello de criatura'),
('Cabello de monstruo'),
('Cabello de shaelmaar'),
('Caparazón de monstruo'),
('Caparazón quitinoso'),
('Capucha de carnicero'),
('Carne cruda'),
('Carne podrida'),
('Cerebro de monstruo'),
('Cerebro de sumergido'),
('Colmillo de jabalí'),
('Colmillo de monstruo'),
('Colmillo de vampiro'),
('Concha de mar'),
('Coraza quitinosa'),
('Corazón de endriago'),
('Corazón de gárgola'),
('Corazón de gólem'),
('Corazón de monstruo'),
('Corazón de nekker'),
('Cuerdas vocales de sirena'),
('Cuero curtido'),
('Dahlia'),
('Descarga de ciempiés gigante'),
('Descarga de kikimora'),
('Desconocida'),
('Desconocido'),
('Devine'),
('Diente de boira'),
('Diente de bruja del agua'),
('Diente de monstruo'),
('Diente falso'),
('Dientes de boira'),
('Dientes de monstruo'),
('Embrión de endriago'),
('Escama plateada de eslizón'),
('Escamas de dragón'),
('Esencia cristalizada'),
('Esencia de agua'),
('Esencia de aparición'),
('Esencia de barghest'),
('Esencia de elemental'),
('Esencia de espectro'),
('Esencia de luz'),
('Esencia de monstruo'),
('Esencia elementa'),
('Esencia elemental'),
('Esencia oscura'),
('Espora de monstruo'),
('Estómago de gallotriz'),
('Estómago de monstruo'),
('Excremento de demonibestia'),
('Extracto de veneno'),
('Fibra'),
('Fósforo'),
('Fragmento infundido'),
('Fragmentos lunares'),
('Garra de alghul'),
('Garra de monstruo'),
('Garra de nekker'),
('Garra de vampiro'),
('Garralarga'),
('Garras de arpía'),
('Glándula salival de criatura'),
('Grasa de oso'),
('Hacha enana'),
('Hígado de guerrero nekker'),
('Hígado de lobo'),
('Hígado de monstruo'),
('Hígado de trol de cueva'),
('Hueso de monstruo'),
('Huevo de arpía'),
('Huevo de gallotriz'),
('Huevo de grifo'),
('Huevo de wyverno'),
('Jugo de arquespor'),
('Lengua de monstruo'),
('Lengua de sumergido'),
('Llave asquerosa de criatura'),
('Llave de la guarida del katakan'),
('Madera endurecida'),
('Mandíbula de ciempiés gigante'),
('Mechón de pelo de lamia'),
('Médula de alghul'),
('Mineral de hierro'),
('Mutágeno azul'),
('Mutágeno azul menor'),
('Mutágeno azul pequeño'),
('Mutágeno azul superior'),
('Mutágeno de alghul'),
('Mutágeno de aparición'),
('Mutágeno de aparición nocturna'),
('Mutágeno de arachas'),
('Mutágeno de archigrifo'),
('Mutágeno de basilisco'),
('Mutágeno de boira'),
('Mutágeno de bruja del agua'),
('Mutágeno de bruja sepulcral'),
('Mutágeno de chort'),
('Mutágeno de colihendido'),
('Mutágeno de dama del mediodía'),
('Mutágeno de demonibestia'),
('Mutágeno de doppler'),
('Mutágeno de ekhidna'),
('Mutágeno de ekimmara'),
('Mutágeno de elemental de tierra'),
('Mutágeno de gallotriz'),
('Mutágeno de grifo'),
('Mutágeno de guerrero nekker'),
('Mutágeno de hombre lobo'),
('Mutágeno de katakan'),
('Mutágeno de leshen'),
('Mutágeno de leshen antiguo'),
('Mutágeno de protofleder'),
('Mutágeno de súcubo'),
('Mutágeno de trol'),
('Mutágeno de wyverno'),
('Mutágeno rojo'),
('Mutageno rojo menor'),
('Mutágeno rojo pequeño'),
('Mutágeno rojo superior'),
('Mutágeno verde'),
('Mutágeno verde menor'),
('Mutágeno verde pequeño'),
('Ojo de demonibestia'),
('Ojo de erynia'),
('Ojo de monstruo'),
('Ojos de arachas'),
('Ojos de cíclope'),
('Ojos de nekker'),
('Oreja de bruja sepulcral'),
('Oreja de criatura'),
('Oreja de monstruo'),
('Orens'),
('Pala del guardián'),
('Pantalones de Mahakam'),
('Pelo de aparición nocturna'),
('Pelo de monstruo'),
('Piedra rúnica de Dazhbog superior'),
('Piedra rúnica de Triglav superior'),
('Piedras rúnicas'),
('Piel de basilisco'),
('Piel de chort'),
('Piel de colihendido'),
('Piel de ekimmara'),
('Piel de endriago'),
('Piel de hombre lobo'),
('Piel de jabalí'),
('Piel de lobo'),
('Piel de monstruo'),
('Piel de necrófago'),
('Piel de oso'),
('Piel de oso blanco'),
('Piel de oso vieja'),
('Piel de trol'),
('Piel de wyverno'),
('Pieles de chort'),
('Pluma de monstruo'),
('Plumas de arpía'),
('Plumas de grifo'),
('Polvo de amatista'),
('Polvo de aparición'),
('Polvo de esmeralda'),
('Polvo de espectro'),
('Polvo de gárgola'),
('Polvo de shaelmaar'),
('Polvo infundido'),
('Polvo mágico'),
('Quintaesencia'),
('Resina de leshen'),
('Sacacorchos'),
('Saliva de hombre lobo'),
('Saliva de monstruo'),
('Saliva de vampiro'),
('Sangre de demonio podrido'),
('Sangre de devorador'),
('Sangre de ghul'),
('Sangre de monstruo'),
('Sangre de nekker'),
('Sangre de vampiro'),
('Sebo de perro'),
('Tangalore:'),
('Tapas de botella'),
('Tejido de monstruo en polvo'),
('Tenedor'),
('Trofeo de aparición'),
('Trofeo de aparición nocturna'),
('Trofeo de arachas'),
('Trofeo de boira'),
('Trofeo de bruja del agua'),
('Trofeo de bruja sepulcral'),
('Trofeo de Cavernoso'),
('Trofeo de chort'),
('Trofeo de colihendido'),
('Trofeo de criatura'),
('Trofeo de dama del mediodía'),
('Trofeo de demonibestia'),
('Trofeo de doppler'),
('Trofeo de ekhidna'),
('Trofeo de ekimmara'),
('Trofeo de elemental de tierra'),
('Trofeo de eslizón'),
('Trofeo de gallotriz'),
('Trofeo de garkain'),
('Trofeo de Golyat'),
('Trofeo de grifo'),
('Trofeo de guerrero nekker'),
('Trofeo de katakan'),
('Trofeo de leshen'),
('Trofeo de pesanta'),
('Trofeo de sabueso de la cacería salvaje'),
('Trofeo de shaelmaar'),
('Trofeo de trol de cueva'),
('Trofeo de wyverno'),
('Trozo de piel'),
('Veneno de arachas'),
('Veneno de basilisco'),
('Zarcillo de arquespor'),
('Fragmento impregnado');